//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by common.rc
//
#define IDD_DLG_MAIN                    101
#define IDI_ICON1                       106
#define IDD_MSG                         107
#define IDD_DLG_TEMPLATE                109
#define IDR_MENU_OTHER                  111
#define IDD_DLG_TIMEOUTS                114
#define IDR_MENU_MORE                   116
#define IDD_DLG_PINCTRL                 117
#define IDD_DLG_EXPR                    118
#define IDR_MENU_EDIT_RECV              120
#define IDD_DLG_STR2HEX                 122
#define IDD_DLG_MONITOR                 125
#define IDD_CMD                         127
#define IDD_SEND_CMD                    128
#define IDD_CMD_TEMPLATE                129
#define IDR_ACCELERATOR1                130
#define IDD_DIALOG1                     131
#define IDD_GETBR                       131
#define IDC_BTN_SEND                    1000
#define IDC_MSG_OK                      1001
#define IDC_CBO_CP                      1002
#define IDC_CBO_BR                      1005
#define IDC_CBO_CHK                     1006
#define IDC_CBO_DATA                    1007
#define IDC_CBO_STOP                    1008
#define IDC_BTN_OPEN                    1009
#define IDC_EDIT_RECV                   1010
#define IDC_EDIT_SEND                   1011
#define IDC_CHK_AUTO_SEND               1012
#define IDC_EDIT_DELAY                  1013
#define IDC_RADIO_SEND_HEX              1014
#define IDC_RADIO_SEND_CHAR             1015
#define IDC_RADIO_RECV_HEX              1016
#define IDC_RADIO_RECV_CHAR             1017
#define IDC_CHK_TOP                     1018
#define IDC_STATIC_STATUS               1019
#define IDC_BTN_CLR_RECV                1020
#define IDC_BTN_CLR_SEND                1021
#define IDC_BTN_CLR_COUNTER             1022
#define IDC_BTN_HELP                    1023
#define IDC_BTN_COPY_RECV               1024
#define IDC_MSG_EDIT_MSG                1025
#define IDC_BTN_COPY_SEND               1026
#define IDC_BTN_SAVEFILE                1027
#define IDC_MSG_HOTLINK                 1028
#define IDC_BTN_STOPDISP                1029
#define IDC_BTN_LOADFILE                1030
#define IDC_HOOK_COMBO                  1031
#define IDC_HOOK_STATIC                 1032
#define IDC_EDIT_RECV2                  1033
#define IDC_STATIC_VERSION              1034
#define IDC_BTN_MORE_SETTINGS           1035
#define IDC_CTO_EDIT_READ_INTERVAL      1036
#define IDC_CTO_EDIT_READ_MULTIPLIER    1037
#define IDC_CTO_EDIT_READ_CONSTANT      1038
#define IDC_CTO_EDIT_WRITE_MULTIPLIER   1039
#define IDC_CTO_EDIT_WRITE_CONSTANT     1040
#define IDC_CTO_BTN_OK                  1041
#define IDC_CTO_BTN_CANCEL              1042
#define IDC_CTO_BTN_DEFAULT             1043
#define IDC_PINCTRL_OK                  1044
#define IDC_CBO_PINCTRL_DTR             1045
#define IDC_CBO_PINCTRL_RTS             1046
#define IDC_EXPR_EDIT_EXPR              1047
#define IDC_EXPR_EDIT_RESULT            1048
#define IDC_STATIC_RECV                 1049
#define IDC_STATIC_TIMER                1050
#define IDC_EDIT_STR2HEX_SRC            1051
#define IDC_EDIT_STR2HEX_DST            1052
#define IDC_EDIT_MONITOR_RECV           1053
#define IDC_STATIC_PICTURE              1054
#define IDC_STATIC_SEND                 1056
#define IDC_CMD_CMDLIST                 1057
#define IDC_CMD_DATA                    1058
#define IDC_CMD_SEND                    1059
#define IDC_CHECK_IGNORE_RETURN         1060
#define IDC_CHECK2                      1061
#define IDC_CHECK_USE_ESCAPE_CHAR       1061
#define IDC_CMD_STATIC_TYPE             1062
#define IDC_CMD_STATIC_SIZE             1064
#define IDC_CMD_EDIT_CMD                1065
#define IDC_CMD_BUTTON_SEND             1066
#define IDC_CMD_STATIC_NAME             1067
#define IDC_BUTTON1                     1068
#define IDC_BUTTON2                     1069
#define IDC_EDIT1                       1070
#define MENU_OTHER_ASCII                40001
#define MENU_OTHER_HELP                 40002
#define MENU_OTHER_CALC                 40003
#define MENU_OTHER_NOTEPAD              40004
#define MENU_MORE_TIMEOUTS              40005
#define MENU_MORE_DRIVER                40006
#define MENU_MORE_PINCTRL               40007
#define MENU_OTHER_DEVICEMGR            40008
#define ID_POPUPMENU_40009              40009
#define MENU_EDIT_CHINESE               40010
#define ID_POPUPMENU_40011              40011
#define MENU_OTHER_STR2HEX              40012
#define ID_POPUPMENU_40013              40013
#define MENU_OTHER_MONITOR              40014
#define ID_POPUPMENU_40015              40015
#define MENU_OTHER_DRAW                 40016
#define ID_POPUPMENU_40017              40017
#define MENU_OTHER_NEWVERSION           40018
#define IDACC_SEND                      40021
#define IDACC_OPEN                      40022
#define IDACC_STOPDISP                  40023
#define IDACC_CLRCOUNTER                40024

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        132
#define _APS_NEXT_COMMAND_VALUE         40028
#define _APS_NEXT_CONTROL_VALUE         1071
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
