//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by common.rc
//
#define IDD_DLG_MAIN                    101
#define IDI_ICON1                       106
#define IDR_MENU_OTHER                  111
#define IDD_DLG_TIMEOUTS                114
#define IDR_MENU_MORE                   116
#define IDD_DLG_PINCTRL                 117
#define IDD_SEND_CMD                    128
#define IDR_ACCELERATOR1                130
#define IDD_DIALOG1                     131
#define IDD_GETBR                       131
#define IDR_101                         134
#define IDR_102                         135
#define IDR_RCDATA2                     137
#define MENU_EDIT_CONTEXTMENU           138
#define MENU_RICHEDIT_CONTEXTMENU       138
#define IDD_DIALOG2                     139
#define IDD_TEMPLATE                    139
#define IDR_MENU_SENDCMD                140
#define IDC_BTN_SEND                    1000
#define IDC_CBO_CP                      1002
#define IDC_CBO_BR                      1005
#define IDC_CBO_CHK                     1006
#define IDC_CBO_DATA                    1007
#define IDC_CBO_STOP                    1008
#define IDC_BTN_OPEN                    1009
#define IDC_EDIT_RECV                   1010
#define IDC_EDIT_SEND                   1011
#define IDC_CHK_AUTO_SEND               1012
#define IDC_EDIT_DELAY                  1013
#define IDC_RADIO_SEND_HEX              1014
#define IDC_RADIO_SEND_CHAR             1015
#define IDC_RADIO_RECV_HEX              1016
#define IDC_RADIO_RECV_CHAR             1017
#define IDC_CHK_TOP                     1018
#define IDC_STATIC_STATUS               1019
#define IDC_BTN_CLR_RECV                1020
#define IDC_BTN_CLR_SEND                1021
#define IDC_BTN_CLR_COUNTER             1022
#define IDC_BTN_HELP                    1023
#define IDC_BTN_COPY_RECV               1024
#define IDC_BTN_COPY_SEND               1026
#define IDC_BTN_SAVEFILE                1027
#define IDC_BTN_STOPDISP                1029
#define IDC_BTN_LOADFILE                1030
#define IDC_EDIT_RECV2                  1033
#define IDC_BTN_MORE_SETTINGS           1035
#define IDC_CTO_EDIT_READ_INTERVAL      1036
#define IDC_CTO_EDIT_READ_MULTIPLIER    1037
#define IDC_CTO_EDIT_READ_CONSTANT      1038
#define IDC_CTO_EDIT_WRITE_MULTIPLIER   1039
#define IDC_CTO_EDIT_WRITE_CONSTANT     1040
#define IDC_CTO_BTN_OK                  1041
#define IDC_CTO_BTN_CANCEL              1042
#define IDC_CTO_BTN_DEFAULT             1043
#define IDC_PINCTRL_OK                  1044
#define IDC_CBO_PINCTRL_DTR             1045
#define IDC_CBO_PINCTRL_RTS             1046
#define IDC_STATIC_RECV                 1049
#define IDC_STATIC_TIMER                1050
#define IDC_STATIC_PICTURE              1054
#define IDC_STATIC_SEND                 1056
#define IDC_CMD_STATIC_TYPE             1062
#define IDC_CMD_STATIC_SIZE             1064
#define IDC_CMD_EDIT_CMD                1065
#define IDC_CMD_BUTTON_SEND             1066
#define IDC_CMD_STATIC_NAME             1067
#define IDC_BUTTON1                     1068
#define IDC_BTN_SEND_FMT_CONFIG         1068
#define IDC_BUTTON2                     1069
#define MAINSTATIC_CP                   1071
#define MAINSTATIC_BR                   1072
#define MAINSTATIC_CHK                  1073
#define MAINSTATIC_DATABIT              1074
#define MAINSTATIC_STOPBIT              1075
#define MAINSTATIC_TIMER                1076
#define MAINSTATIC_RECV_FORMAT          1077
#define MAINSTATIC_SEND_FORMAT          1078
#define MAINSTATIC_AUTOSEND             1079
#define IDC_CHECK_SIMPLE                1081
#define IDC_CHECK2                      1085
#define MENU_OTHER_ASCII                40001
#define MENU_OTHER_HELP                 40002
#define MENU_OTHER_CALC                 40003
#define MENU_OTHER_NOTEPAD              40004
#define MENU_MORE_TIMEOUTS              40005
#define MENU_MORE_DRIVER                40006
#define MENU_MORE_PINCTRL               40007
#define MENU_OTHER_DEVICEMGR            40008
#define ID_POPUPMENU_40009              40009
#define ID_POPUPMENU_40011              40011
#define MENU_OTHER_STR2HEX              40012
#define ID_POPUPMENU_40013              40013
#define MENU_OTHER_MONITOR              40014
#define ID_POPUPMENU_40015              40015
#define MENU_OTHER_DRAW                 40016
#define ID_POPUPMENU_40017              40017
#define MENU_OTHER_NEWVERSION           40018
#define IDACC_SEND                      40021
#define IDACC_OPEN                      40022
#define IDACC_STOPDISP                  40023
#define IDACC_CLRCOUNTER                40024
#define ID_POPUPMENU_40028              40028
#define ID_POPUPMENU_40030              40030
#define ID_POPUPMENU_40032              40032
#define ID_EDITCONTEXTMENU_COPY         40039
#define ID_EDITCONTEXTMENU_CUT          40040
#define ID_EDITCONTEXTMENU_PASTE        40041
#define ID_EDITCONTEXTMENU_DELETE       40042
#define ID_EDITCONTEXTMENU_SELALL       40043
#define ID_EDITCONTEXTMENU_FULLSCREEN   40044
#define ID_40046                        40046
#define ID_40047                        40047
#define MENU_SENDCMD_NEWCMD             40048
#define MENU_SENDCMD_COLLAPSEALL        40049

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        141
#define _APS_NEXT_COMMAND_VALUE         40050
#define _APS_NEXT_CONTROL_VALUE         1091
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
