#ifndef _COMMON_EX_DEFINED_
#define _COMMON_EX_DEFINED_
#include <windows.h>
#include <winioctl.h>

#define FILE_DEVICE_COMMON	0x00001001

#define IOCTL_COMMON_STARTMONITOR	CTL_CODE(FILE_DEVICE_COMMON, 0x0801, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_COMMON_STOPMONITOR	CTL_CODE(FILE_DEVICE_COMMON, 0x0802, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_COMMON_GETINFOSIZE	CTL_CODE(FILE_DEVICE_COMMON, 0x0803, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_COMMON_GETINFO		CTL_CODE(FILE_DEVICE_COMMON, 0x0804, METHOD_BUFFERED, FILE_ANY_ACCESS)

typedef ULONG MHANDLE;

enum
{
	REQ_OPEN,
	REQ_READ,
	REQ_WRITE,
	REQ_CLOSE,
	REQ_FLUSH,
	REQ_SETBAUDRATE,
	REQ_SETLINECONTROL,
};

typedef struct
{
	DWORD Reserved1;
	DWORD Reserved2;
	DWORD Reserved3;
	ULONG SizeRequested,SizeCopied;
	CHAR type;
}IOReq;

typedef struct _SERIAL_LINE_CONTROL {
    UCHAR StopBits;
    UCHAR Parity;
    UCHAR WordLength;
    } SERIAL_LINE_CONTROL,*PSERIAL_LINE_CONTROL;

#endif	// _COMMON_EX_DEFINED_
